export const MessageTypes = {
    DOWNLOADING: "DOWNLOADING",
    LOADING: "LOADING",
    RESULT: "RESULT",
    RESULT_PARTIAL: "RESULT_PARTIAL",
    INFERENCE_REQUEST: "INFERENCE_REQUEST",
    INFERENCE_DONE: "INFERENCE_DONE",
};

export const LoadingStatus = {
    SUCCESS: "success",
    ERROR: "error",
    LOADING: "loading",
};

export const ModelNames = {
    WHISPER_TINY: "Xenova/whisper-tiny",
    WHISPER_BASE: "Xenova/whisper-base",
    WHISPER_SMALL: "Xenova/whisper-small",
    WHISPER_MEDIUM: "Xenova/whisper-medium",
    WHISPER_LARGE_V3: "Xenova/whisper-large-v3", // Current - Best accuracy
    NLLB_600M: "Xenova/nllb-200-distilled-600M",
    NLLB_1_3B: "Xenova/nllb-200-1.3B" // Current - Best translation quality
};

export const LANGUAGES = {
    "English": "eng_Latn",
    "Spanish": "spa_Latn",
    "French": "fra_Latn",
    "German": "deu_Latn",
    "Italian": "ita_Latn",
    "Portuguese": "por_Latn",
    "Dutch": "nld_Latn",
    "Russian": "rus_Cyrl",
    "Polish": "pol_Latn",
    "Ukrainian": "ukr_Cyrl",
    "Czech": "ces_Latn",
    "Romanian": "ron_Latn",
    "Greek": "ell_Grek",
    "Mandarin Chinese (Simplified)": "zho_Hans",
    "Mandarin Chinese (Traditional)": "zho_Hant",
    "Japanese": "jpn_Jpan",
    "Korean": "kor_Hang",
    "Vietnamese": "vie_Latn",
    "Thai": "tha_Thai",
    "Indonesian": "ind_Latn",
    "Malay": "zsm_Latn",
    "Tagalog": "tgl_Latn",
    "Hindi": "hin_Deva",
    "Bengali": "ben_Beng",
    "Urdu": "urd_Arab",
    "Punjabi": "pan_Guru",
    "Marathi": "mar_Deva",
    "Telugu": "tel_Telu",
    "Tamil": "tam_Taml",
    "Gujarati": "guj_Gujr",
    "Kannada": "kan_Knda",
    "Malayalam": "mal_Mlym",
    "Arabic": "arb_Arab",
    "Hebrew": "heb_Hebr",
    "Persian": "pes_Arab",
    "Turkish": "tur_Latn",
    "Swahili": "swh_Latn",
    "Hausa": "hau_Latn",
    "Yoruba": "yor_Latn",
    "Zulu": "zul_Latn",
    "Afrikaans": "afr_Latn",
    "Amharic": "amh_Ethi",
    "Swedish": "swe_Latn",
    "Norwegian": "nob_Latn",
    "Danish": "dan_Latn",
    "Finnish": "fin_Latn",
    "Hungarian": "hun_Latn",
    "Bulgarian": "bul_Cyrl",
    "Serbian": "srp_Cyrl",
    "Croatian": "hrv_Latn",
    "Slovak": "slk_Latn",
    "Slovenian": "slv_Latn",
};
